# AthleteIQ Data Preprocessing

## Objective

Prepare the sleep and lifestyle dataset for machine learning by cleaning the data, handling missing values, transforming variables, and creating a processed dataset.

### Preprocessing Tasks

- Load the raw dataset
- Inspect the dataset
- Remove unnecessary columns
- Split Blood Pressure into numeric features
- Standardize BMI categories
- Handle missing values
- Check for duplicates
- Save the processed dataset

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("../data/raw/Sleep_health_and_lifestyle_dataset.csv")

df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [7]:
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())
print("\nData types:")
print(df.dtypes)

Dataset shape: (374, 13)

Column names:
['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps', 'Sleep Disorder']

Data types:
Person ID                    int64
Gender                         str
Age                          int64
Occupation                     str
Sleep Duration             float64
Quality of Sleep             int64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                   str
Blood Pressure                 str
Heart Rate                   int64
Daily Steps                  int64
Sleep Disorder                 str
dtype: object

In [8]:
# Create a copy of the raw dataset for preprocessing
df_processed = df.copy()

df_processed.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [9]:
# Remove the identifier column
df_processed = df_processed.drop(columns=["Person ID"])

df_processed.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [10]:
print(df_processed["BMI Category"].value_counts())

BMI Category
Normal           195
Overweight       148
Normal Weight     21
Obese             10
Name: count, dtype: int64

In [11]:
# Standardize BMI category names
df_processed["BMI Category"] = df_processed["BMI Category"].replace(
    {"Normal Weight": "Normal"}
)

print(df_processed["BMI Category"].value_counts())

BMI Category
Normal        216
Overweight    148
Obese          10
Name: count, dtype: int64

In [12]:
# Split Blood Pressure into two numeric columns
df_processed[["Systolic BP", "Diastolic BP"]] = (
    df_processed["Blood Pressure"]
    .str.split("/", expand=True)
    .astype(int)
)

df_processed[["Blood Pressure", "Systolic BP", "Diastolic BP"]].head()

  Blood Pressure  Systolic BP  Diastolic BP
0         126/83          126            83
1         125/80          125            80
2         125/80          125            80
3         140/90          140            90
4         140/90          140            90

In [13]:
# Remove the original Blood Pressure column
df_processed = df_processed.drop(columns=["Blood Pressure"])

df_processed.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic BP,Diastolic BP
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,NaN,126,83
1,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125,80
2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125,80
3,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90
4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90

In [14]:
print(df_processed.isnull().sum())

Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
Systolic BP                  0
Diastolic BP                 0
dtype: int64

In [15]:
# Replace missing sleep disorder values with "None"
df_processed["Sleep Disorder"] = df_processed["Sleep Disorder"].fillna("None")

print(df_processed["Sleep Disorder"].value_counts())

Sleep Disorder
None           219
Sleep Apnea     78
Insomnia        77
Name: count, dtype: int64

In [16]:
print(df_processed.isnull().sum())

Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
Systolic BP                0
Diastolic BP               0
dtype: int64

In [17]:
print("Number of duplicate rows:", df_processed.duplicated().sum())

Number of duplicate rows: 242

In [18]:
print("Final dataset shape:", df_processed.shape)

df_processed.info()

Final dataset shape: (374, 13)
<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   374 non-null    str
 1   Age                      374 non-null    int64
 2   Occupation               374 non-null    str
 3   Sleep Duration           374 non-null    float64
 4   Quality of Sleep         374 non-null    int64
 5   Physical Activity Level  374 non-null    int64
 6   Stress Level             374 non-null    int64
 7   BMI Category             374 non-null    str
 8   Heart Rate               374 non-null    int64
 9   Daily Steps              374 non-null    int64
 10  Sleep Disorder           374 non-null    str
 11  Systolic BP              374 non-null    int64
 12  Diastolic BP             374 non-null    int64
dtypes: float64(1), int64(8), str(4)
memory usage: 38.1 KB

In [19]:
df_processed.head()

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic BP,Diastolic BP
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,None,126,83
1,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,None,125,80
2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,None,125,80
3,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90
4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90

## Preprocessing Summary

The dataset was prepared for machine learning through the following steps:

- Removed `Person ID` because it is only an identifier and does not provide useful predictive information.
- Standardized the `BMI Category` values by combining `Normal Weight` with `Normal`.
- Split `Blood Pressure` into two numerical variables: `Systolic BP` and `Diastolic BP`.
- Removed the original `Blood Pressure` text column.
- Replaced missing values in `Sleep Disorder` with `None`.
- Checked the dataset for remaining missing values.
- Checked for duplicate records.
- Created a cleaned dataset ready for the next stage of feature preparation and machine learning.

In [20]:
# Save the processed dataset
df_processed.to_csv(
    "../data/processed/processed_sleep_health_dataset.csv",
    index=False
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.

In [21]:
# Load the saved dataset to verify it was saved correctly
df_check = pd.read_csv("../data/processed/processed_sleep_health_dataset.csv")

print(df_check.shape)
df_check.head()

(374, 13)

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic BP,Diastolic BP
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,NaN,126,83
1,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125,80
2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125,80
3,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90
4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140,90